SELECT 
C.CID, C.CName, C.CAddress, C.CPN,  
TG.TGID, TG.TGName, TG.TGPN, A.AAddress,
R.RID, R.RDate, R.SumR                   
FROM RECEIPT R
JOIN CUSTOMER C ON R.CID = C.CID
JOIN AGENCY A ON R.AID = A.AID
JOIN TOURGUIDE TG ON TG.AID = A.AID
WHERE R.RDate = '2026-05-24';
