CREATE DATABASE BAITAPLON
GO
USE BAITAPLON
GO
CREATE TABLE CUSTOMER(
	CID CHAR(6) PRIMARY KEY,
	CName VARCHAR(30) NOT NULL,
	CAddress VARCHAR(50) NOT NULL,
	CPN VARCHAR(12)
)
GO
CREATE TABLE HOTEL(
	HID VARCHAR(15) PRIMARY KEY,
	HName VARCHAR(30) NOT NULL,
	CIDate DATETIME NOT NULL,
	CODate DATETIME NOT NULL,
	HAddress VARCHAR(50)
)
GO
CREATE TABLE TOUR(
	TID CHAR(6) PRIMARY KEY,
	TName NVARCHAR(30) NOT NULL,
	Price MONEY NOT NULL,
	SDate DATE NOT NULL,
	EDate DATE NOT NULL,
	HID VARCHAR(15) NOT NULL,
	CONSTRAINT HOTEL_TOUR FOREIGN KEY(HID) REFERENCES HOTEL(HID)
)
GO
CREATE TABLE AGENCY(
	AID VARCHAR(10) PRIMARY KEY,
	APN VARCHAR(12),
	AAddress VARCHAR(50) NOT NULL
)
GO
CREATE TABLE TOURGUIDE(
	TGID CHAR(5) PRIMARY KEY,
	TGName NVARCHAR(30) NOT NULL,
	TGPN VARCHAR(12),
	AID VARCHAR(10) NOT NULL,
	CONSTRAINT TOURGUIDE_AGENCY FOREIGN KEY(AID) REFERENCES AGENCY(AID)
)
GO
CREATE TABLE SALARY(
	SIDTG CHAR(5) PRIMARY KEY,
	TGS MONEY NOT NULL,
	TGID CHAR(5) NOT NULL,
	CONSTRAINT FK_SALARY_TOURGUID FOREIGN KEY(TGID) REFERENCES TOURGUIDE(TGID)
)
GO
CREATE TABLE RECEIPT(
	RID CHAR(7) PRIMARY KEY,
	RDate DATE NOT NULL,
	SumR MONEY NOT NULL,
	CID CHAR(6) NOT NULL,
	AID VARCHAR(10) NOT NULL,
	CONSTRAINT RECEIPT_CUSTOMER FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
	CONSTRAINT RECEIPT_AGENCY FOREIGN KEY(AID) REFERENCES AGENCY(AID)
)
GO
CREATE TABLE VEHICLE(
	LicensePlate VARCHAR(15) PRIMARY KEY,
	VType VARCHAR(20) NOT NULL
)
GO
CREATE TABLE GOBY(
	TID CHAR(6) NOT NULL,
	LicensePlate VARCHAR(15) NOT NULL,
	PRIMARY KEY (TID,LicensePlate),
	CONSTRAINT VEHICLE_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_VEHICLE FOREIGN KEY(LicensePlate) REFERENCES VEHICLE(LicensePlate)
)
GO
CREATE TABLE TLOCATION(
	LID VARCHAR(10) PRIMARY KEY,
	LName VARCHAR(30) NOT NULL,
	Province VARCHAR(15) NOT NULL
)
GO
CREATE TABLE COME(
	TID CHAR(6) NOT NULL,
	LID VARCHAR(10) NOT NULL,
	PRIMARY KEY (TID,LID),
	CONSTRAINT TLOCATION_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_TLOCATION FOREIGN KEY(LID) REFERENCES TLOCATION(LID)
)
GO
CREATE TABLE ASSIGN(
	TID CHAR(6) NOT NULL,
	TGID CHAR(5) NOT NULL,
	PRIMARY KEY (TID,TGID),
	CONSTRAINT TOURGUIDE_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_TOURGUIDE FOREIGN KEY(TGID) REFERENCES TOURGUIDE(TGID)
)
GO
CREATE TABLE BOOKING(
	TID CHAR(6) NOT NULL,
	CID CHAR(6) NOT NULL,
	PRIMARY KEY (TID,CID),
	CONSTRAINT CUSTOMER_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_CUSTOMER FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)
)
CREATE DATABASE BAITAPLON
GO
USE BAITAPLON
GO
CREATE TABLE CUSTOMER(
	CID CHAR(6) PRIMARY KEY,
	CName VARCHAR(30) NOT NULL,
	CAddress VARCHAR(50) NOT NULL,
	CPN VARCHAR(12)
)
GO
CREATE TABLE HOTEL(
	HID VARCHAR(15) PRIMARY KEY,
	HName VARCHAR(30) NOT NULL,
	CIDate DATETIME NOT NULL,
	CODate DATETIME NOT NULL,
	HAddress VARCHAR(50)
)
GO
CREATE TABLE TOUR(
	TID CHAR(6) PRIMARY KEY,
	TName NVARCHAR(30) NOT NULL,
	Price MONEY NOT NULL,
	SDate DATE NOT NULL,
	EDate DATE NOT NULL,
	HID VARCHAR(15) NOT NULL,
	CONSTRAINT HOTEL_TOUR FOREIGN KEY(HID) REFERENCES HOTEL(HID)
)
GO
CREATE TABLE AGENCY(
	AID VARCHAR(10) PRIMARY KEY,
	APN VARCHAR(12),
	AAddress VARCHAR(50) NOT NULL
)
GO
CREATE TABLE TOURGUIDE(
	TGID CHAR(5) PRIMARY KEY,
	TGName NVARCHAR(30) NOT NULL,
	TGPN VARCHAR(12),
	AID VARCHAR(10) NOT NULL,
	CONSTRAINT TOURGUIDE_AGENCY FOREIGN KEY(AID) REFERENCES AGENCY(AID)
)
GO
CREATE TABLE SALARY(
	SIDTG CHAR(5) PRIMARY KEY,
	TGS MONEY NOT NULL,
	TGID CHAR(5) NOT NULL,
	CONSTRAINT FK_SALARY_TOURGUID FOREIGN KEY(TGID) REFERENCES TOURGUIDE(TGID)
)
GO
CREATE TABLE RECEIPT(
	RID CHAR(7) PRIMARY KEY,
	RDate DATE NOT NULL,
	SumR MONEY NOT NULL,
	CID CHAR(6) NOT NULL,
	AID VARCHAR(10) NOT NULL,
	CONSTRAINT RECEIPT_CUSTOMER FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
	CONSTRAINT RECEIPT_AGENCY FOREIGN KEY(AID) REFERENCES AGENCY(AID)
)
GO
CREATE TABLE VEHICLE(
	LicensePlate VARCHAR(15) PRIMARY KEY,
	VType VARCHAR(20) NOT NULL
)
GO
CREATE TABLE GOBY(
	TID CHAR(6) NOT NULL,
	LicensePlate VARCHAR(15) NOT NULL,
	PRIMARY KEY (TID,LicensePlate),
	CONSTRAINT VEHICLE_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_VEHICLE FOREIGN KEY(LicensePlate) REFERENCES VEHICLE(LicensePlate)
)
GO
CREATE TABLE TLOCATION(
	LID VARCHAR(10) PRIMARY KEY,
	LName VARCHAR(30) NOT NULL,
	Province VARCHAR(15) NOT NULL
)
GO
CREATE TABLE COME(
	TID CHAR(6) NOT NULL,
	LID VARCHAR(10) NOT NULL,
	PRIMARY KEY (TID,LID),
	CONSTRAINT TLOCATION_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_TLOCATION FOREIGN KEY(LID) REFERENCES TLOCATION(LID)
)
GO
CREATE TABLE ASSIGN(
	TID CHAR(6) NOT NULL,
	TGID CHAR(5) NOT NULL,
	PRIMARY KEY (TID,TGID),
	CONSTRAINT TOURGUIDE_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_TOURGUIDE FOREIGN KEY(TGID) REFERENCES TOURGUIDE(TGID)
)
GO
CREATE TABLE BOOKING(
	TID CHAR(6) NOT NULL,
	CID CHAR(6) NOT NULL,
	PRIMARY KEY (TID,CID),
	CONSTRAINT CUSTOMER_TOUR FOREIGN KEY(TID) REFERENCES TOUR(TID),
	CONSTRAINT TOUR_CUSTOMER FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)
)
